[phases.setup]
# This commit hash contains Node 22.13+
nixPkgsArchive = '51ad838b03a05b1de6f9f2a0fffecee64a9788ee'

# CHANGED: used underscore, removed the "-x" suffix
nixPkgs = ['nodejs_22', 'npm-9_x']
nixLibs = ['nodejs_22']
